# Generated by Django 2.2.19 on 2023-10-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('phase_value', models.PositiveSmallIntegerField(choices=[(0, 'LOCAL'), (2, '1 фаза'), (3, '2 фаза'), (4, '3 фаза'), (5, '4 фаза'), (6, '5 фаза'), (7, '6 фаза'), (8, '7 фаза'), (1, '0 фаза')], verbose_name='Phase')),
            ],
            options={
                'verbose_name': 'Техническая координация.',
                'verbose_name_plural': 'Техническая координация',
            },
        ),
    ]
