# Generated by Django 4.2.11 on 2024-07-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_central_protocol_alter_central_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
    ]
