# Generated by Django 4.2.11 on 2024-07-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_phaseparameterset"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtcParameterSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("num_controllers", models.IntegerField()),
                ("timeout", models.IntegerField()),
                ("data", models.JSONField()),
            ],
        ),
    ]
