# Generated by Django 4.2.11 on 2024-08-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0004_utcparameterset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveConfigFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to="conflicts/configs/",
                        verbose_name="config_file",
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                (
                    "controller_type",
                    models.CharField(
                        db_index=True, default="undefind", max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaveConflictsTXT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to="conflicts/txt/",
                        verbose_name="txt_files",
                    ),
                ),
                ("time_create", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="phaseparameterset",
            options={
                "verbose_name": "Сохранение полей excel скрипта",
                "verbose_name_plural": "Сохранение полей excel скрипта",
            },
        ),
        migrations.AlterModelOptions(
            name="utcparameterset",
            options={
                "verbose_name": "Сохранение полей phase_control",
                "verbose_name_plural": "Сохранение полей phase_control",
            },
        ),
    ]
