# Generated by Django 4.2.11 on 2024-12-02 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0006_alter_saveconfigfiles_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saveconfigfiles",
            name="adress",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saveconfigfiles",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="saveconfigfiles",
            name="ip_adress",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="saveconfigfiles",
            name="number",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="saveconfigfiles",
            name="file",
            field=models.FileField(
                null=True,
                upload_to="conflicts/configs/",
                verbose_name="config_file",
            ),
        ),
        migrations.AlterField(
            model_name="saveconfigfiles",
            name="time_create",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
