# Generated by Django 4.2.11 on 2025-01-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tools",
            "0007_saveconfigfiles_adress_saveconfigfiles_description_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SaveConfigFiles",
        ),
    ]
