# Generated by Django 3.2.16 on 2023-10-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Правила', 'verbose_name_plural': 'Правила'},
        ),
    ]
