# Generated by Django 3.2.16 on 2023-10-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_rule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='responsible',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
