# Generated by Django 4.2.11 on 2024-11-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_auto_20231005_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
