# Generated by Django 4.2.11 on 2024-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ControllerManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "num_visible_hosts",
                    models.IntegerField(blank=True, default=1),
                ),
                ("data", models.TextField(unique=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("category", models.IntegerField()),
                ("user_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TrafficLightObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=0, unique=True)),
                ("description", models.CharField(max_length=30)),
                ("type_controller", models.CharField(max_length=10)),
                ("group", models.IntegerField(default=0)),
                ("ip_adress", models.CharField(max_length=12, unique=True)),
                ("adress", models.TextField(blank=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
                ("connection", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-time_create"],
                "indexes": [
                    models.Index(
                        fields=["-time_create"],
                        name="toolkit_tra_time_cr_95dbb4_idx",
                    )
                ],
            },
        ),
    ]
