# Generated by Django 4.2.11 on 2024-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0002_testtrafficlightobjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegrammUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=10, unique=True)),
                ("username", models.CharField(max_length=40, null=True)),
                ("first_name", models.CharField(max_length=40, null=True)),
                ("last_name", models.CharField(max_length=40, null=True)),
                ("access_level", models.IntegerField(default=0)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrafficLightsObjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(null=True)),
                ("type_controller", models.CharField(max_length=20)),
                ("group", models.IntegerField(default=0)),
                ("ip_adress", models.CharField(max_length=20, null=True)),
                ("adress", models.TextField(blank=True, null=True)),
                ("time_create", models.DateTimeField(auto_now_add=True)),
                ("time_update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="TestTrafficLightObjects",
        ),
        migrations.DeleteModel(
            name="TrafficLightObjects",
        ),
        migrations.AlterField(
            model_name="controllermanagement",
            name="user_name",
            field=models.CharField(default="0", max_length=20),
        ),
    ]
