# Generated by Django 4.2.11 on 2025-01-30 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0003_telegrammusers_trafficlightsobjects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveConfigFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=20)),
                (
                    "file",
                    models.FileField(
                        null=True,
                        upload_to="conflicts/configs/",
                        verbose_name="config_file",
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "controller_type",
                    models.CharField(
                        db_index=True, default="undefined", max_length=20
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("number", models.CharField(max_length=100, null=True)),
                ("ip_adress", models.CharField(max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrafficLightConfigurator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        max_length=255, verbose_name="Тип запроса"
                    ),
                ),
                (
                    "condition_string",
                    models.TextField(verbose_name="Условие из tlc"),
                ),
                (
                    "function_values",
                    models.TextField(
                        default="",
                        max_length=255,
                        verbose_name="Значения функций",
                    ),
                ),
                (
                    "condition_string_for_parse",
                    models.TextField(
                        default="",
                        verbose_name="Условие с заданными значениями функций",
                    ),
                ),
                (
                    "tokens",
                    models.TextField(
                        default="",
                        max_length=255,
                        verbose_name="Функции(токены) из условия tlc",
                    ),
                ),
                (
                    "result_condition_value",
                    models.BooleanField(
                        default="",
                        null=True,
                        verbose_name="Результат выражения условия из tlc для заданных функций",
                    ),
                ),
                (
                    "errors",
                    models.CharField(max_length=255, verbose_name="Ошибки"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
            ],
        ),
    ]
